#!/bin/bash

echo "💳 Setting up Razorpay Payment Integration for ISOWS-INDIA"
echo "========================================================"
echo ""

# Check if .env file exists
if [ ! -f ".env" ]; then
    echo "📋 Creating .env file from example.env..."
    cp example.env .env
    echo "✅ .env file created"
else
    echo "✅ .env file already exists"
fi

echo ""
echo "🔧 Razorpay Configuration Required:"
echo "=================================="
echo ""
echo "To enable payments, you need to configure Razorpay in your .env file:"
echo ""
echo "1. Create a Razorpay account at https://razorpay.com"
echo "2. Get your API keys from the Razorpay Dashboard:"
echo "   - Go to Settings > API Keys"
echo "   - Copy your Key ID (rzp_test_...)"
echo "   - Copy your Key Secret"
echo ""
echo "3. Set up webhooks:"
echo "   - Go to Settings > Webhooks"
echo "   - Add endpoint: https://your-domain.com/api/payment/webhook"
echo "   - Select events: payment.captured, subscription.*"
echo "   - Copy the webhook secret"
echo ""
echo "📝 Example .env configuration:"
echo "RAZORPAY_KEY_ID=rzp_test_1Abc123..."
echo "RAZORPAY_KEY_SECRET=your_secret_key_here"
echo "RAZORPAY_WEBHOOK_SECRET=your_webhook_secret_here"
echo ""
echo "🔒 Security Notes:"
echo "- Never commit your .env file to version control"
echo "- Use test keys for development"
echo "- Switch to live keys only for production"
echo ""
echo "💰 Payment Plans Configured:"
echo ""
echo "📝 For Writers & Creators:"
echo "- Starter: ₹99/month (2 licenses, 1000 words each)"
echo "- Standard: ₹499/month (5 licenses, 2500 words each) ⭐ Most Popular"
echo "- Premium: ₹999/month (8000 words per file)"
echo "- Pro: ₹1999/month (25 licenses, unlimited words + API)"
echo ""
echo "🔌 For Developers (API):"
echo "- API Starter: ₹999/month (500 API calls)"
echo "- API Unlimited: ₹1999/month (unlimited API calls)"
echo ""
echo "🏢 Enterprise: Contact us for custom pricing"
echo ""
echo "🇮🇳 Indian Payment Methods Supported:"
echo "- Credit/Debit Cards (Visa, MasterCard, RuPay)"
echo "- UPI (Google Pay, PhonePe, Paytm)"
echo "- Net Banking (All major banks)"
echo "- Wallets (Paytm, Mobikwik, Freecharge)"
echo "- EMI options available"
echo ""
echo "✅ Razorpay setup instructions complete!"
echo "   Edit your .env file with the Razorpay credentials above."
echo ""
echo "🚀 Next Steps:"
echo "1. Configure Razorpay keys in .env"
echo "2. Test payments in development mode"
echo "3. Set up webhooks for production"
echo "4. Deploy with live keys for production"
